### PR TITLE
LPS-109292 - SF

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:search

**Comment by thektan** [comment]
@marcoscv-work Thanks again for the fix and creating the ticket! In regards to the search widgets, the changes look good and the test failures are unrelated.

It seems the changes from https://github.com/thektan/liferay-portal/pull/151 are still required though.

Could you confirm and if so you can send those commits along with the changes in this PR to upstream?

Thanks! 🙌

**Comment by marcoscv-work** [comment]
@thektan we can go ahead with this PR, everything looks solved, some here in Spain had problems making ant all and some classes were lost, if we return to detect those errors we will take care of them.

Thanks a lot!

**Comment by thektan** [comment]
Sounds good! I'll go ahead and close this PR.

**Comment by thektan** [comment]
Just to confirm, you guys will be handling the forwarding of the PR?

**Comment by marcoscv-work** [comment]
Of course:
https://github.com/brianchandotcom/liferay-portal/pull/85310

**Pull request closed without merging**
