### PR TITLE
LPS-109168 - Fix button style

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
Hi @marcoscv-work! 

Thanks for the PR! Unfortunately, it doesn't seem this fixes the button. It seems the styles for `.btn:not(.btn-monospaced) {` are causing the issue.

Screen Shot 2020-02-24 at 2 42 44 PM

**Comment by thektan** [comment]
Ah actually @oliv-yu notified me about https://github.com/brianchandotcom/liferay-portal/pull/85150 so this should be good. 👌

**Comment by thektan** [comment]
@marcoscv-work I'm not sure if we want to create a separate ticket for this, but I noticed the `.input-group-inset-item` in `_custom_properties_set.scss` is overriding the `.input-group-inset-item-before`. styles causing the "Left Aligned Icon Layout" to look like this (notice the styling around the search icon):
Screenshot 2020-02-24 16 14 35

These are the styles being applied:
Screenshot 2020-02-24 16 14 28

**Comment by marcoscv-work** [comment]
@thektan yes, it is a new issue. Could you create it? I will try to fix it as soon as possible by adding the exception in custom properties.

I'm closing this LPS :-)

**Comment by marcoscv-work** [comment]
New PR here: https://github.com/thektan/liferay-portal/pull/156

**Pull request closed without merging**
