### PR TITLE
LPS-110463 portal-search-web: Update validation

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-110463

Very small update, but let me know if there's anything else? Also was checking if anywhere else would need a check for null, but not sure.

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:search:norebase

**Comment by oliv-yu** [comment]
ci:test:sf:norebase

**Comment by thektan** [comment]
Reviewed the ci test search results from https://github.com/arboliveira/liferay-portal/pull/809#issuecomment-600713195 and since there aren't any logic changes I'm going to go ahead and send this to bchan.

**Comment by thektan** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86574.

**Pull request closed without merging**
