### PR TITLE
LPS-99430 portal-search-tuning-rankings-web: Use ClayManagementToolbar

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-99430

Most of the keyboard shortcut functionality was ok, except for focusing on the modal and some accessibility warnings (updating to ClayManagementToolbar addressed some of those warnings).

Also will check back on https://github.com/liferay/clay/issues/2578#issuecomment-543907012

@jonmak08

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
Looks like portal shows tooltips for management bars. "Toggle Dropdown" is a bit strange, so let's change this to "Actions" instead since that's what the rest of portal calls the additional dropdown actions.

Screen Shot 2019-10-23 at 5 00 45 PM

Everything else looks good!

**Comment by oliv-yu** [comment]
Done! Thanks for finding

**Comment by thektan** [comment]
Don't forget to run `yarn test`. :)

```
    > 171 | 		fireEvent.click(getByTitle('toggle-dropdown'));
          | 		                ^
```

**Comment by oliv-yu** [comment]
Oops... resent!

**Comment by thektan** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80004. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
