### PR TITLE
LPS-95372 portal-search-web: Remove view of 'Access Denied' warning

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-95372

Slight change to hide the error message "you don't have permissions" :)

@jonmak08

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf:norebase

**Comment by oliv-yu** [comment]
ci:test:search:norebase

**Comment by thektan** [comment]
ci:stop

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86440.

**Pull request closed without merging**
