### PR TITLE
LPS-104941 - Fix result rankings test async timeout error in CI (Frontend Jest Test)

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-104941

Running tests.

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
@joshchong The changes shouldn't be related, but I thought I'd bring this failure to your attention unless it's a fluke in `LocalFile.Search#SearchDifferentScopesViaSearchWidget` in https://github.com/thektan/liferay-portal/pull/105#issuecomment-564284054.

**Comment by joshchong** [comment]
@thektan thanks for the heads up!

**Comment by thektan** [comment]
Submitted: https://github.com/brianchandotcom/liferay-portal/pull/81847

**Pull request closed without merging**
