### PR TITLE
LPS-106087 - As a search developer, I want to use ADTs to customize the Search Result Widget

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-106087

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
@timpak Could you validate that these are known issues? https://github.com/thektan/liferay-portal/pull/123#issuecomment-574406871

**Comment by timpak** [comment]
hey @thektan the failures are either known issues or flukes. no failures were caused by your changes

**Comment by thektan** [comment]
ci:test:bundle

**Pull request closed without merging**
