### PR TITLE
LPS-100106 - SF

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
@julien @carloslancha Thanks! The changes look good. Is this good to forward to BChan?

**Comment by julien** [comment]
@thektan yes please, thanks.

**Comment by thektan** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78080. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
