### PR TITLE
LPS-107306 portal-search-tuning-synonyms-web:unit test changes for fixing unsupportedOpeerationException with Solr

### PR DESCRIPTION
**Pull request by wcao20170619**

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:search-solr

**Comment by thektan** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:search-es7

**Comment by joshchong** [comment]
@wcao20170619 @thektan I took a look at the ci:test:search-solr results and unfortunately this issue is still occurring, but at a later point in the test. Instead of the `UnsupportedOperationException` occurring during startup, they are now occurring when the user is using Portal. Unfortunately I am unable to give details on what the user is doing since the tests aborts due to the errors and is unable to generate test results. You can see examples of this within the console logs of any of the aborted `functional-tomcat90-mysql57-jdk8` batches here:
https://test-1-15.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2052/jenkins-report.html

**Comment by thektan** [comment]
@wcao20170619 Looks like we need the check on `onBeforeRemove` as well? I'll assign this ticket back to you. 

Here are 2 stack trace snippets that might be useful:
```
[exec] 00:57:32,240 ERROR [http-nio-8080-exec-11][EditInstanceMVCActionCommand:121] java.lang.UnsupportedOperationException
     [exec] java.lang.UnsupportedOperationException
     [exec] 	at com.liferay.portal.search.solr7.internal.search.engine.adapter.index.IndicesExistsIndexRequestExecutorImpl.execute(IndicesExistsIndexRequestExecutorImpl.java:33)
     [exec] 	at com.liferay.portal.search.solr7.internal.search.engine.adapter.index.SolrIndexRequestExecutor.executeIndexRequest(SolrIndexRequestExecutor.java:118)
     [exec] 	at com.liferay.portal.search.engine.adapter.index.IndicesExistsIndexRequest.accept(IndicesExistsIndexRequest.java:34)
     [exec] 	at com.liferay.portal.search.engine.adapter.index.IndicesExistsIndexRequest.accept(IndicesExistsIndexRequest.java:22)
     [exec] 	at com.liferay.portal.search.solr7.internal.search.engine.adapter.SolrSearchEngineAdapterImpl.execute(SolrSearchEngineAdapterImpl.java:75)
     [exec] 	at com.liferay.portal.search.tuning.synonyms.web.internal.index.SynonymSetIndexReaderImpl.isExists(SynonymSetIndexReaderImpl.java:59)
     [exec] 	at com.liferay.portal.search.tuning.synonyms.web.internal.index.creation.model.listener.SynonymSetIndexCreationCompanyModelListener.onBeforeRemove(SynonymSetIndexCreationCompanyModelListener.java:67)
     [exec] 	at com.liferay.portal.search.tuning.synonyms.web.internal.index.creation.model.listener.SynonymSetIndexCreationCompanyModelListener.onBeforeRemove(SynonymSetIndexCreationCompanyModelListener.java:38)
     [exec] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.remove(BasePersistenceImpl.java:470)
     [exec] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.doDeleteCompany(CompanyLocalServiceImpl.java:1301)
     [exec] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.deleteCompany(CompanyLocalServiceImpl.java:522)
```

I'm not as clear what the issue is for this error though:
```
[exec] 00:59:39,369 ERROR [http-nio-8080-exec-11][PortletServlet:119] javax.portlet.PortletException: java.lang.UnsupportedOperationException
     [exec] javax.portlet.PortletException: java.lang.UnsupportedOperationException
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:69)
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:358)
     [exec] 	at com.liferay.portal.kernel.portlet.LiferayPortlet.processAction(LiferayPortlet.java:88)
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.processAction(MVCPortlet.java:248)
     [exec] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:77)
     [exec] 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:50)
     [exec] 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
```

**Comment by wcao20170619** [comment]
ci:test:search-solr

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:search-es7

**Comment by joshchong** [comment]
@wcao20170619 @thektan the test results lgtm!

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83771.

**Pull request closed without merging**
