### PR TITLE
LPS 104990 language keys

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-104990

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
Sent to bchan, https://github.com/brianchandotcom/liferay-portal/pull/81731

**Pull request closed without merging**
