### PR TITLE
LPS-89920 portal-search-web-api: Add scopeParameterName to search settings

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-89920

@jonmak08

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:search:norebase

**Comment by oliv-yu** [comment]
ci:test:sf:norebase

**Comment by thektan** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86350.

**Comment by thektan** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86358. [See changes here.](https://github.com/thektan/liferay-portal/compare/9e87206475d8~1...9e87206475d8)

**Pull request closed without merging**
