### PR TITLE
LPS-61272

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @thektan,

Attached is an update for http://issues.liferay.com/browse/LPS-61272.  We need to add the import packages to the bnd files for the modules that are using the ratings taglib.

Can you do that and send this to @jbalsas?

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
Hey @jonmak08, In regards to adding the import-package declaration in bnds, I think Chema mentioned that it's not necessary because bnd tools will do this automatically.  We should only need to do it if there is an error when the taglib executes, which means bnd tools missed that import for one reason or another.

**Comment by thektan** [comment]
@mjbradford89 During testing there were errors being thrown where certain modules couldn't find the package so @jonmak08 and I agreed that in this case we'll need to add the import to the bnds.

**Comment by mjbradford89** [comment]
Ah I see, never mind then!

**Comment by jbalsas** [comment]
Hey guys! 

This is very interesting... as @mjbradford89 is right, there should be no need for that. Could you guys please identify the offending modules and add the imports? I'll go over them with Miguel to see what's the problem and wether it could/should be fixed.

Thanks a lot!

**Comment by thektan** [comment]
@jbalsas I just tested it again and for me only the message-boards-web module needs the import. I think @jonmak08 was getting an error for most/all of the modules using the ratings taglib, but I'll have to check in with him again.

**Comment by mjbradford89** [comment]
Thanks @jbalsas!

FYI, I also still have to explicitly import the taglib packages that I'm using.  At least for the current taglib I'm migrating.  Which is the discussion taglib, I have to import it's package `com.liferay.comment.taglib.servlet.taglib`, in comment-page-comments/bnd.bnd for it to work in that bundle.

**Comment by thektan** [comment]
@jonmak08 What is the purpose of d041ca8 (LPS-61272 - Migrate ui:ratings to modules/apps/ratings)? Should that be combined with e30a068 (LPS-61272 - General source formatting) or is there some other purpose for that commit?

**Comment by jonmak08** [comment]
Hey @thektan,

Yea, https://github.com/thektan/liferay-portal/commit/d041ca84b2011e685d18951d9fb966aedf2c211a and https://github.com/thektan/liferay-portal/commit/e30a068513ce03a1795ee9f8258bea0bf74db725 should be squished into the "General source formatting" commit.  Can you update the commits before sending it to @jbalsas?

Please let me know if you have any questions.  Thanks!

**Comment by thektan** [comment]
New pull request: https://github.com/jbalsas/liferay-portal/pull/326

**Pull request closed without merging**
