### PR TITLE
LPS-92008 Make search widgets invisible

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-92008

Will also fix https://issues.liferay.com/browse/LPS-81279

Modified facet, Suggestions, and Search Results will be visible once they have content to display. I didn't include Custom Filter because its invisibility is decided with configurations.

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search:norebase

**Comment by thektan** [comment]
Pull request submitted to https://github.com/arboliveira/liferay-portal/pull/749. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
