### PR TITLE
LPS-120653 remove dark navbar

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-120653

For reference, view_results_rankings and view_synonym_sets were renamed to view.jsp, since the original view.jsp was mostly just the navbar.

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:forward

**Comment by thektan** [comment]
ci:forward

**Comment by xbrianlee** [comment]
The issues above are either known issues documented in the test analysis spreadsheet or unrelated failures. . Also this PR should have forwarded since there were no unique failures in [this run](https://github.com/thektan/liferay-portal/pull/205#issuecomment-695156300).

**Comment by thektan** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/94466.

**Pull request closed without merging**
