### PR TITLE
LPS-104938 - As a Search Admin, I want to see connection info for currently active connections

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-104938

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by suilin** [comment]
ci:test:search-es7

**Comment by suilin** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
running new tests here https://github.com/BryanEngler/liferay-portal/pull/470

**Pull request closed without merging**
