### PR TITLE
LPS-107432 - Compile failure on apps:portal-search:portal-search-web:compileTestJava

### PR DESCRIPTION
**Pull request by arboliveira**
From: https://github.com/thektan/liferay-portal/pull/128

http://issues.liferay.com/browse/LPS-107432

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf:norebase

**Comment by arboliveira** [comment]
ci:test:search:norebase

**Comment by thektan** [comment]
Pull request submitted to https://github.com/thektan/liferay-portal/pull/131.

**Comment by thektan** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83664.

**Pull request closed without merging**
