### PR TITLE
LPS-109100 Enable scrolling for Add Result modal

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-109100

Now you can scroll for modal buttons :)

@jonmak08

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf:norebase

**Comment by oliv-yu** [comment]
ci:test:search:norebase

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85868.

**Pull request closed without merging**
