### PR TITLE
Lps 142996 edit element preview error

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-142996 - Unable to load preview content message

Error was occurring because of missing availableLanguages in the theme context! I just made it default to `{}` but let me know if it is better to actually define the availableLanguages in the elements editor theme context.

Thanks!

### CODE REVIEW

**Comment by thektan** [comment]
Shouldn't the available languages be defined in the ThemeContext that wraps the whole page? It should be using the global (something like) Liferay.ThemeDisplay.availableLanguages. And if not, the defaults should be set in the ThemeDisplay.is file.

**Comment by oliv-yu** [comment]
Ah, so in the `edit_sxp_element/index.js` the theme context is defined like this:
`<ThemeContext.Provider
			value={{
				defaultLocale,
				namespace,
				redirectURL,
			}}
		>`

Maybe that's why the defaults aren't applied? I can add availableLanguages in here if that works better.

**Comment by thektan** [comment]
Ya since it can pull the value from JS already (like not requiring a server
request) we should just add it. Check the formatting of how the object is
shaped though, it might have needed a translating function.

**Comment by oliv-yu** [comment]
Added! Not sure if it needed a translating function? Let me know later if it's ok.

**Comment by thektan** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/110826

**Pull request closed without merging**
