### PR TITLE
LPS-61844 Migrate asset-addon-entry-selector to asset-taglib module

### PR DESCRIPTION
**Pull request by tylerwonglr**
Hey Kevin Tan!  

Please check the PR for the asset-addon-entry-selector!

https://issues.liferay.com/browse/LPS-61844

Thanks!
Tyler

### CODE REVIEW

**Comment by thektan** [comment]
New pull request sent: https://github.com/jonmak08/liferay-portal/pull/1434

**Comment by thektan** [comment]
@tylerwonglr Testing

**Comment by thektan** [comment]
@tylerwonglr another test

**Comment by tylerwonglr** [comment]
@thektan testing

**Comment by tylerwonglr** [comment]
@tylerwonglr testinggggg

**Comment by thektan** [comment]
@tylerwonglr test test

**Comment by thektan** [comment]
@tylerwonglr asdf

**Comment by thektan** [comment]
@tylerwonglr 2

**Comment by thektan** [comment]
@tylerwonglr 3

**Comment by thektan** [comment]
@tylerwonglr 4

**Comment by thektan** [comment]
@tylerwonglr 5

**Comment by thektan** [comment]
@tylerwonglr 6

**Comment by tylerwonglr** [comment]
@thektan 1

**Comment by tylerwonglr** [comment]
@thektan 2

**Comment by tylerwonglr** [comment]
@thektan 3

**Comment by tylerwonglr** [comment]
@thektan 4

**Comment by tylerwonglr** [comment]
@thektan 5

**Comment by tylerwonglr** [comment]
@thektan 6

**Comment by tylerwonglr** [comment]
@thektan 7

**Comment by tylerwonglr** [comment]
@thektan 8

**Comment by tylerwonglr** [comment]
@thektan 9

**Comment by tylerwonglr** [comment]
@thektan 10

**Comment by tylerwonglr** [comment]
@tylerwonglr 1

**Comment by tylerwonglr** [comment]
@tylerwonglr 2

**Comment by tylerwonglr** [comment]
@tylerwonglr 3

**Comment by tylerwonglr** [comment]
@tylerwonglr 4

**Comment by tylerwonglr** [comment]
@tylerwonglr 5

**Comment by tylerwonglr** [comment]
@tylerwonglr 6

**Comment by tylerwonglr** [comment]
@tylerwonglr 7

**Comment by tylerwonglr** [comment]
@tylerwonglr 78

**Comment by tylerwonglr** [comment]
@tylerwonglr 79

**Comment by tylerwonglr** [comment]
@tylerwonglr 710

**Comment by tylerwonglr** [comment]
@tylerwonglr 711

**Comment by tylerwonglr** [comment]
@tylerwonglr 712

**Comment by tylerwonglr** [comment]
@tylerwonglr not working

**Comment by thektan** [comment]
@tylerwonglr 1

**Comment by thektan** [comment]
@tylerwonglr 2

**Comment by thektan** [comment]
@tylerwonglr 3

**Comment by thektan** [comment]
@tylerwonglr 4

**Comment by thektan** [comment]
@tylerwonglr 5

**Comment by thektan** [comment]
@tylerwonglr 1

**Comment by thektan** [comment]
@tylerwonglr 2

**Comment by thektan** [comment]
@tylerwonglr 3

**Comment by thektan** [comment]
@tylerwonglr 4

**Comment by thektan** [comment]
@tylerwonglr 5

**Comment by thektan** [comment]
@tylerwonglr 6

**Comment by thektan** [comment]
@tylerwonglr 7

**Comment by thektan** [comment]
@tylerwonglr 8

**Comment by thektan** [comment]
@tylerwonglr 9

**Comment by thektan** [comment]
@tylerwonglr 10

**Pull request closed without merging**
