### PR TITLE
LPS-107010 - Result Rankings: Generic error UX when attempting to activate duplicate ranking

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-107010

Running tests again and then will send to BChan.

Squashed a few commits together. @oliv-yu

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf:norebase

**Comment by thektan** [comment]
ci:test:search:norebase

**Comment by thektan** [comment]
ci:test:bundle

**Comment by joshchong** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:close

Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/84352

**Pull request closed without merging**
